# Generated by Django 4.2.7 on 2025-12-06 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Дата платежа')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Запланированная сумма')),
                ('description', models.CharField(default='Платеж по кредиту', max_length=200, verbose_name='Описание платежа')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплаченная сумма')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'График платежей',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата транзакции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('category', models.CharField(choices=[('Food', 'Еда'), ('Transport', 'Транспорт'), ('Communication', 'Связь'), ('Entertainment', 'Развлечения'), ('Shopping', 'Покупки'), ('Bills', 'Коммунальные услуги'), ('Other', 'Прочее')], max_length=20, verbose_name='Категория')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('currency_code', models.CharField(choices=[('USD', 'Доллар США'), ('EUR', 'Евро')], max_length=3, verbose_name='Код валюты')),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс покупки')),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс продажи')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date'],
                'unique_together': {('date', 'currency_code')},
            },
        ),
    ]
