# Generated by Django 4.2.7 on 2025-12-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
